export const APIendpoints = {
    lookupType: '/advancesearch/lookupdetails?lookupType=',
    accessorialAttachments: '/accessorial/accessorialdocumentdetails?ServiceExceptionId=',
    getAccessoeials: '/accessorial/pendingaccessorial',
    getAccessorialsGridColumns: '/advancesearch/HeaderPreference?SegmentValue=',
    accessorialOpenFile: '/accessorial/accessorialdocument?serviceExpDocId=',
    addAccessorialComments: '/accessorial/addaccessorialcomments',
    accessorialDetails: '/accessorial/accessorialdetails?ServiceExceptionId=',
    accessorialComments: '/accessorial/accessorialcomments?ServiceExceptionId=',
    getAccessorialsPendingPaginationData: '/accessorial/pendingaccessorialpagination',
    getPreference: '/preference/preferencedetails?PreferenceType=',
    getUserPreference:'/preference/GetUserPreferences/',
    SaveUserPreferenceLocation:'/preference/SaveUserPreferenceLocation',
    savePreferences:'/preference/UpdateUserPreferences/',
    //getMenuLists: '/preference/GetMenuLists/',
    deleteLocation:'/preference/DeleteuserPreferenceLocation/',
    draftoderdetails: '/submitorder/draftoderdetails',
    saveorderlineitem: '/submitorder/saveorderlineitem',
    saveorderdetails: '/submitorder/saveorderdetails',
    saveorderorigin: '/submitorder/saveorderorigin',
    saveorderdestination: '/submitorder/saveorderdestination',
    saveorderadditionalifo: '/submitorder/saveorderadditionalifo',
    orderstepper: '/submitorder/orderstepper?orderId=',
    getaddinfo: '/submitorder/getorderaddinfo',
    saveaddinfo: '/submitorder/saveorderadditionalifo',
    deleteComments: '/submitorder/deleteordercomment?CommentId=',
    getorderlineitems: '/submitorder/getorderlinedetails?orderId=',
    deleteorderlineitems: '/submitorder/deleteorderline?OrderLineID=',
    getorderdetailsdata: '/submitorder/getorderdetails?orderId=',
    deleterefnum: '/submitorder/deleterefnum?ReferenceId=',
    opendocument: '/submitorder/orderdocuments?DocId=',
    deleteAttachments: '/submitorder/deleteorderdoc?DocumentId=',
    getIncidentGridColumns:'/advancesearch/HeaderPreference?SegmentValue=',
    getUserNotifications: '/notification/UserNotifications',
    updateUserNotification: '/notification/updateusernotification/',
    deleteIncidentDoc: '/incident/deletedocument?documentId=',
    getReport:'/preference/GetKibanaReportDetails',
    daylookup:'/advancesearch/lookupdetails/?lookupType=notification-filter'
}