export const RouteLinks = {
    reportincidentdisplayrecord: '/dashboard/reportincidentdisplayrecord',
    approveaccessorialDetails: '/dashboard/approveaccessorialDetails',
    reportincidentadvancesearch: '/dashboard/reportincidentadvancesearch',
    approveAccessrialsGrid: '/dashboard/approve-accessorials',
    dashboard: '/dashboard',
    viewOrderDetail: '/dashboard/vieworderdetails',
    bulkSearch: '/dashboard/bulksearch',
    securetrackorder: '/dashboard/securetrackorder',
    accessdocument: '/dashboard/accessdocument',
    advanceSearchDocument: '/dashboard/advancesearchdocument',
    searchandreport: '/dashboard/searchandreport',
    advanceSearchOrder:'/dashboard/advancesearchorder',
    publicorderdetails: '/publicorderdetails',
    submitordergrid: 'dashboard/submitordergrid',
    submitordermain: 'dashboard/submitordermain',
    userPreference: '/dashboard/userPreference',
    viewallnotifications:'/dashboard/viewallnotifications',
    login: '/login',
    orderDetails: '/dashboard/orderdetails',
    incidentgrid: 'dashboard/incidentgrid',
    reportIncident: 'dashboard/reportincident',
    registration:'/registration',
}